### ISSUE TITLE
[ UI ]: Add hero section in showcase archive page

### ISSUE THREAD

**Issue by ashiishme** [askbuddie/showcase#36]
Font family:  Raleway
Font size: 50px
Font weight:  Extra Bold ( use in numbers )

Colors:
Text dark: #2D2D2D
Text brand: #E53935

Brand with opacity: #E53935 ( 5% )

<img width="885" alt="Screen Shot 2021-10-09 at 8 10 17 AM" src="https://user-images.githubusercontent.com/18111862/136640753-ebcc66ac-dc4a-40bc-a429-5a5bd98ac494.png">

**Comment by ayushkarn32** [comment]
i don't see any page named archive is it index.js where this hero section needs to be added ?

**Comment by LaxmanJonchhen12** [comment]
I can work on it

**Comment by ayushkarn32** [comment]
even i am working

**Comment by ayushkarn32** [comment]
@LaxmanJonchhen12 yes i am trying xd

**Comment by LaxmanJonchhen12** [comment]
@ayushkarn32 ok you can do it as you have already started

**Comment by ashiishme** [comment]
Then I will assign it to Ayush @LaxmanJonchhen12

**Comment by ashiishme** [comment]
@ayushkarn32 Have you joined Ask Buddie Discord server? You can ask questions there if you have any.

**Comment by ayushkarn32** [comment]
@ashiishme sir please check the pull request

**Comment by ashiishme** [comment]
Thank you @ayushkarn32  for your contribution.
